version: '2'
services:
  local-mysql-database:
    image: mysql/mysql-server:5.7
    container_name: local-mysql-database
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: starterspringkotlin
      MYSQL_DATABASE: starterspringkotlin
